[features]
seeds = false
[programs.localnet]
aureus = "6RfngPJpgsk6NunDQrDqVForuVy7G5v4McctZuAGM84a"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/teknas/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
